name: Release
permissions: {}

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      packages: write
      contents: write
      # Required for OIDC.
      # See: https://docs.npmjs.com/trusted-publishers
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - run: ./zig/download.sh
      - run: ./zig/zig build scripts -- release --build --sha=${{ github.sha }} --language=zig
      - run: ./zig/zig build scripts -- release --publish --sha=${{ github.sha }} --language=docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  alert_failure:
    runs-on: ubuntu-latest
    needs: [release]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Alert if anything failed
        run: |
          export URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" && \
          curl -d "text=Release process for ${{ github.run_number }} failed! See ${URL} for more information." -d "channel=C04RWHT9EP5" -H "Authorization: Bearer ${{ secrets.SLACK_TOKEN }}" -X POST https://slack.com/api/chat.postMessage
